name: PR File Diff Check After Merge

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    

jobs:
  diff-check:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    name: Check diff in files after PR merge to develop
    runs-on: ubuntu-latest

    steps:
      # Checkout the develop branch and fetch history
      - name: Checkout base branch (develop)
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      # Show the diff in files after the PR is merged
      - name: Show file differences after merge
        run: git diff --name-status HEAD~1 HEAD

